version: "3"

services:
  api:
    build: .
    ports:
      - 4000:3000
    volumes:
      - .:/usr/src/app
    environment:
      PORT: 3000
      JWT_SECRET: ${JWT_SECRET}
      MONGODB_URL: ${MONGODB_URL}
      
    